[package]
name = "cli_tree"
version = "0.1.0"
edition = "2021"
authors = ["Eric (Sk3pz) skepz.dev@gmail.com"]
description = "A CLI tool to generate a tree of user defined nodes"
homepage = ""
readme = "README.md"
license = "MIT"

[dependencies]
