[package]
name = "cli_tree"
version = "1.0.0"
edition = "2021"
authors = ["Eric (Sk3pz) skepz.dev@gmail.com"]
description = "A CLI tool to generate a tree of user defined nodes"
homepage = "github.com/sk3pz/cli_tree"
readme = "README.md"
license = "MIT"

[dependencies]
